### ISSUE TITLE
no implicit conversion of nil into String

### ISSUE THREAD

**Issue by lundstrj** [fastlane-community/fastlane-plugin-s3#107]
I've run into an issue in Fastlane where aws_s3 fails with a rather cryptic `no implicit conversion of nil into String`.
This is my first time using Fastlane (and ruby) so please forgive me if this is simple 101 stuff (searching didn't yield any useful hits. I suppose it is possible I was searching for the wrong things).

Here is a bit more context:
`[19:45:00]: ------------------------------------------------
[19:45:00]: --- Step: echo $XCODEBUILD_DERIVED_DATA_PATH ---
[19:45:00]: ------------------------------------------------
[19:45:00]: $ echo $XCODEBUILD_DERIVED_DATA_PATH
[19:45:00]: ▸ /Users/distiller/super_secret_app/ios/build/
[19:45:00]:
[19:45:00]: /Users/distiller/super_secret_app/ios/build/
[19:45:00]: ENDOFOUTPUT
[19:45:00]: --------------------
[19:45:00]: --- Step: aws_s3 ---
[19:45:00]: --------------------
+------------------------------------+--------------------------------------------------------------------------------------+
|                                                       Lane Context                                                        |
+------------------------------------+--------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM                   | ios                                                                                  |
| PLATFORM_NAME                      | ios                                                                                  |
| LANE_NAME                          | ios simulator                                                                        |
| KEYCHAIN_PATH                      | ~/Library/Keychains/fastlane_tmp_keychain                                            |
| ORIGINAL_DEFAULT_KEYCHAIN          | "/Users/distiller/Library/Keychains/fastlane_tmp_keychain-db"                        |
| SIGH_PROFILE_TYPE                  | development                                                                          |
| MATCH_PROVISIONING_PROFILE_MAPPING | {"com.foo.super_secret_app"=>"match Development com.foo.super_secret_app"} |
| XCODEBUILD_DERIVED_DATA_PATH       | /Users/distiller/super_secret_app/ios/build/                                       |
+------------------------------------+--------------------------------------------------------------------------------------+
[19:45:00]: no implicit conversion of nil into String

+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | default_platform                                              | 0           |
| 2    | setup_circle_ci                                               | 0           |
| 3    | match                                                         | 2           |
| 4    | xcodebuild                                                    | 16          |
| 5    | zip -r /Users/distiller/super_secret_app/ios/Debug-iphonesi | 2           |
| 6    | echo $XCODEBUILD_DERIVED_DATA_PATH                            | 0           |
| 💥   | aws_s3                                                        | 0           |
+------+---------------------------------------------------------------+-------------+

[19:45:00]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Deliverfile api_key: connect_api/token.rb:62:in `binread': [!] no implicit conversion of nil into String
    https://github.com/fastlane/fastlane/issues/19348 [closed] 1 💬
    3 weeks ago

➡️  google_cloud_storage TypeError: [!] no implicit conversion of nil into String
    https://github.com/fastlane/fastlane/issues/16836 [closed] 10 💬
    20 Oct 2020

➡️  latest_testflight_build_number receiving error: [!] no implicit conversion of Integer into String
    https://github.com/fastlane/fastlane/issues/17161 [closed] 10 💬
    04 Nov 2020

and 89 more at: https://github.com/fastlane/fastlane/search?q=no%20implicit%20conversion%20of%20nil%20into%20String&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/Users/distiller/.gem/ruby/2.7.3/bin/fastlane)
Traceback (most recent call last):
	49: from /Users/distiller/.gem/ruby/2.7.3/bin/bundle:23:in `<main>'
	48: from /Users/distiller/.gem/ruby/2.7.3/bin/bundle:23:in `load'
	47: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/exe/bundle:37:in `<top (required)>'
	46: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
	45: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/exe/bundle:49:in `block in <top (required)>'
	44: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/cli.rb:24:in `start'
	43: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	42: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/cli.rb:30:in `dispatch'
	41: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	40: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	39: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	38: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/cli.rb:474:in `exec'
	37: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/cli/exec.rb:28:in `run'
	36: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/cli/exec.rb:63:in `kernel_load'
	35: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/cli/exec.rb:63:in `load'
	34: from /Users/distiller/.gem/ruby/2.7.3/bin/fastlane:23:in `<top (required)>'
	33: from /Users/distiller/.gem/ruby/2.7.3/bin/fastlane:23:in `load'
	32: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/bin/fastlane:23:in `<top (required)>'
	31: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	30: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	29: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	28: from /Users/distiller/.gem/ruby/2.7.3/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	27: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	26: from /Users/distiller/.gem/ruby/2.7.3/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	25: from /Users/distiller/.gem/ruby/2.7.3/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	24: from /Users/distiller/.gem/ruby/2.7.3/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	23: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	22: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	21: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	20: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	19: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	18: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	17: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	16: from Fastfile:80:in `block (2 levels) in parsing_binding'
	15: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	14: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	13: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	12: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	11: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	10: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	 9: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 8: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-plugin-aws_s3-2.0.3/lib/fastlane/plugin/aws_s3/actions/aws_s3_action.rb:100:in `run'
	 7: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-plugin-aws_s3-2.0.3/lib/fastlane/plugin/aws_s3/actions/aws_s3_action.rb:130:in `upload_ipa'
	 6: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-plugin-aws_s3-2.0.3/lib/fastlane/plugin/aws_s3/actions/aws_s3_action.rb:612:in `expand_path_with_substitutions_from_ipa_plist'
	 5: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane_core/lib/fastlane_core/ipa_file_analyser.rb:45:in `fetch_info_plist_file'
	 4: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane_core/lib/fastlane_core/ipa_file_analyser.rb:82:in `fetch_info_plist_with_unzip'
	 3: from /Users/distiller/.rubies/ruby-2.7.3/lib/ruby/2.7.0/open3.rb:281:in `capture3'
	 2: from /Users/distiller/.rubies/ruby-2.7.3/lib/ruby/2.7.0/open3.rb:101:in `popen3'
	 1: from /Users/distiller/.rubies/ruby-2.7.3/lib/ruby/2.7.0/open3.rb:213:in `popen_run'
/Users/distiller/.rubies/ruby-2.7.3/lib/ruby/2.7.0/open3.rb:213:in `spawn': no implicit conversion of nil into String (TypeError)
	49: from /Users/distiller/.gem/ruby/2.7.3/bin/bundle:23:in `<main>'
	48: from /Users/distiller/.gem/ruby/2.7.3/bin/bundle:23:in `load'
	47: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/exe/bundle:37:in `<top (required)>'
	46: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
	45: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/exe/bundle:49:in `block in <top (required)>'
	44: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/cli.rb:24:in `start'
	43: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	42: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/cli.rb:30:in `dispatch'
	41: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	40: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	39: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	38: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/cli.rb:474:in `exec'
	37: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/cli/exec.rb:28:in `run'
	36: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/cli/exec.rb:63:in `kernel_load'
	35: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/cli/exec.rb:63:in `load'
	34: from /Users/distiller/.gem/ruby/2.7.3/bin/fastlane:23:in `<top (required)>'
	33: from /Users/distiller/.gem/ruby/2.7.3/bin/fastlane:23:in `load'
	32: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/bin/fastlane:23:in `<top (required)>'
	31: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	30: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	29: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	28: from /Users/distiller/.gem/ruby/2.7.3/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	27: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	26: from /Users/distiller/.gem/ruby/2.7.3/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	25: from /Users/distiller/.gem/ruby/2.7.3/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	24: from /Users/distiller/.gem/ruby/2.7.3/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	23: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	22: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	21: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	20: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	19: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	18: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	17: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	16: from Fastfile:80:in `block (2 levels) in parsing_binding'
	15: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	14: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	13: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	12: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	11: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	10: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	 9: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 8: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-plugin-aws_s3-2.0.3/lib/fastlane/plugin/aws_s3/actions/aws_s3_action.rb:100:in `run'
	 7: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-plugin-aws_s3-2.0.3/lib/fastlane/plugin/aws_s3/actions/aws_s3_action.rb:130:in `upload_ipa'
	 6: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-plugin-aws_s3-2.0.3/lib/fastlane/plugin/aws_s3/actions/aws_s3_action.rb:612:in `expand_path_with_substitutions_from_ipa_plist'
	 5: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane_core/lib/fastlane_core/ipa_file_analyser.rb:45:in `fetch_info_plist_file'
	 4: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.195.0/fastlane_core/lib/fastlane_core/ipa_file_analyser.rb:82:in `fetch_info_plist_with_unzip'
	 3: from /Users/distiller/.rubies/ruby-2.7.3/lib/ruby/2.7.0/open3.rb:281:in `capture3'
	 2: from /Users/distiller/.rubies/ruby-2.7.3/lib/ruby/2.7.0/open3.rb:101:in `popen3'
	 1: from /Users/distiller/.rubies/ruby-2.7.3/lib/ruby/2.7.0/open3.rb:213:in `popen_run'
/Users/distiller/.rubies/ruby-2.7.3/lib/ruby/2.7.0/open3.rb:213:in `spawn': \e[31m[!] no implicit conversion of nil into String\e[0m (TypeError)`

The relevant part of my Fastfile is here:
`aws_s3(
      access_key: ENV['S3_ACCESS_KEY'],
      secret_access_key: ENV['S3_SECRET_ACCESS_KEY'],
      bucket: 'super_secret-enterprise-apps',
      region: 'eu-west-1',
      ipa: '/Users/distiller/super_secret/ios/Debug-iphonesimulator/super_secret.ipa.zip',
      dsym: '/Users/distiller/super_secret/ios/Debug-iphonesimulator/super_secret.app.dSYM',
      app_directory: 'ios.com.foo.super_secret.simulator',
      upload_metadata: true
    )`

I have redacted app name and company name.

If only I knew what was nil so I could set it. For a moment I thought that XCODEBUILD_DERIVED_DATA_PATH was the issue as it was blank in the Lane Context output but setting it explicitly didn't change anything.

**Comment by lundstrj** [comment]
I also had a peek at `/Users/distiller/.rubies/ruby-2.7.3/lib/ruby/2.7.0/open3.rb` but nothing looked obviously amiss to me.

**Comment by lundstrj** [comment]
Closing due to being very very stale.
