### ISSUE TITLE
SSL_connect returned=1 errno=0 state=error: certificate verify failed (unspecified certificate verification error)

### ISSUE THREAD

**Issue by danielc103** [fastlane-community/fastlane-plugin-s3#90]
Not sure why I'm getting this error, other s3 tools work fine. 

```
Seahorse::Client::NetworkingError: [!] SSL_connect returned=1 errno=0 state=error: certificate verify failed (unspecified certificate verification error)
  /usr/local/lib/ruby/2.6.0/net/protocol.rb:44:in `connect_nonblock'
  /usr/local/lib/ruby/2.6.0/net/protocol.rb:44:in `ssl_socket_connect'
  /usr/local/lib/ruby/2.6.0/net/http.rb:996:in `connect'
  /usr/local/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
  /usr/local/lib/ruby/2.6.0/net/http.rb:925:in `start'
  /usr/local/lib/ruby/2.6.0/delegate.rb:83:in `method_missing'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/seahorse/client/net_http/connection_pool.rb:299:in `start_session'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/seahorse/client/net_http/connection_pool.rb:97:in `session_for'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/seahorse/client/net_http/handler.rb:121:in `session'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/seahorse/client/net_http/handler.rb:73:in `transmit'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/seahorse/client/net_http/handler.rb:47:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/seahorse/client/plugins/content_length.rb:15:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/plugins/s3_signer.rb:103:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/plugins/s3_signer.rb:57:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/plugins/s3_host_id.rb:15:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/xml/error_handler.rb:8:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/transfer_encoding.rb:24:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:10:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/plugins/s3_signer.rb:83:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/plugins/redirects.rb:18:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/retry_errors.rb:346:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/retry_errors.rb:380:in `retry_request'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/retry_errors.rb:368:in `retry_if_possible'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/retry_errors.rb:357:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/retry_errors.rb:380:in `retry_request'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/retry_errors.rb:368:in `retry_if_possible'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/retry_errors.rb:357:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/retry_errors.rb:380:in `retry_request'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/retry_errors.rb:368:in `retry_if_possible'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/retry_errors.rb:357:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/plugins/dualstack.rb:34:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/plugins/accelerate.rb:50:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/plugins/md5s.rb:32:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/plugins/bucket_name_restrictions.rb:24:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/plugins/expect_100_continue.rb:19:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/plugins/bucket_dns.rb:33:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/plugins/bucket_arn.rb:47:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/plugins/iad_regional_endpoint.rb:32:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/rest/handler.rb:8:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/user_agent.rb:11:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/seahorse/client/plugins/endpoint.rb:45:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/param_validator.rb:24:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/plugins/sse_cpk.rb:22:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/plugins/dualstack.rb:26:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/plugins/accelerate.rb:35:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/seahorse/client/plugins/response_target.rb:23:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/seahorse/client/request.rb:70:in `send_request'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/client.rb:9567:in `put_object'
  /usr/local/lib/ruby/gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/bucket.rb:523:in `put_object'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-plugin-aws_s3-1.8.0/lib/fastlane/plugin/aws_s3/actions/aws_s3_action.rb:517:in `upload_file'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-plugin-aws_s3-1.8.0/lib/fastlane/plugin/aws_s3/actions/aws_s3_action.rb:321:in `upload_apk'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-plugin-aws_s3-1.8.0/lib/fastlane/plugin/aws_s3/actions/aws_s3_action.rb:107:in `run'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:40:in `block (2 levels) in parsing_binding'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.149.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.149.1/bin/fastlane:23:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'
```

**Comment by sebsto** [comment]
I have the same error on fastlane 2.195.0. Did you solve this ?

**Comment by danielc103** [comment]
sorry, I don't remember if we ever got this fixed for this specific project.
